### ISSUE TITLE
Can not execute due to compile error

### ISSUE THREAD

**Issue by lempiji** [rejectedsoftware/ddox#201] opened 2018-03-21 08:40 UTC
Thank you for making a very useful tool.
But in my environment, the following error occurs when running `dub build -b ddox` in my package, or `dub build ddox`.

```
Error: module `app` from file source\app.d is specified twice on the command line
```

The environmental information is as follows.
OS: Windows 10
dmd: 2.079.0
dub: 1.8.0

I would like to fix this.
Regards.

**Comment by s-ludwig** [comment] 2018-03-21 10:19
The immediate cause is https://github.com/dlang/dub/issues/1407 (regression in DUB 1.8.0, will be fixed in the next release). Since 1.8.0 is still the latest release version, though, it probably makes sense to still apply the fix here for the time being.

**Closed** 2018-03-21 12:08 UTC
